### ISSUE TITLE
How to setup on arrch64 linux ?? because i don't install tensoflow in this

### ISSUE THREAD

**Issue by Hoangnn30** [sivakumar-mahalingam/passport-mrz-reader#1]

**Comment by sivakumar-mahalingam** [comment]
Tensorflow is mandatory for using the package. Please share screenshot or system message, related to the query

**Comment by Hoangnn30** [comment]
yes , I use pip3 install tensorflow that install

**Comment by sivakumar-mahalingam** [comment]
Could you please share the error detail?

**Comment by sivakumar-mahalingam** [comment]
Updated the repo by replacing tensorflow with onnx
